import { FurnitureType } from './type/typeFurniture';

export const mockFurniture: FurnitureType[] = [
  {
    id: 0,
    category: 'Chairs',
    title: 'Style and Chic',
    price: 230,
    img: './furnitures/chair_styleAndChic.jpg',
  },
  {
    id: 1,
    category: 'Chairs',
    title: 'Comfort and Convenience',
    price: 320,
    img: '../furnitures/chair_comfortAndConvenience.jpg',
  },
  {
    id: 2,
    category: 'Chairs',
    title: 'Comfort and Beauty',
    price: 560,
    img: './furnitures/chair_comfortAndBeauty.jpg',
  },
  {
    id: 3,
    category: 'Chairs',
    title: 'Comfort and Power',
    price: 560,
    img: './furnitures/chair_comfortAndPower.jpg',
  },
  {
    id: 4,
    category: 'Tables',
    title: 'Family Tea Party',
    price: 560,
    img: './furnitures/table_familyTeaParty.jpg',
  },
  {
    id: 5,
    category: 'Tables',
    title: 'Rigor and Minimalism',
    price: 560,
    img: './furnitures/table_rigorAndMinimalism.jpg',
  },
  {
    id: 6,
    category: 'Tables',
    title: 'Family Table',
    price: 560,
    img: './furnitures/table_familyTable.jpg',
  },
  {
    id: 7,
    category: 'Tables',
    title: 'Pink Table',
    price: 560,
    img: './furnitures/table_pinkTable.jpg',
  },
  {
    id: 8,
    category: 'Lamps',
    title: 'Joy',
    price: 125,
    img: './furnitures/lamps_joy.jpg',
  },
  {
    id: 9,
    category: 'Lamps',
    title: 'Star Light',
    price: 125,
    img: './furnitures/lamps_starLight.jpg',
  },
  {
    id: 10,
    category: 'Lamps',
    title: 'Tower of Light',
    price: 125,
    img: './furnitures/lamps_towerOfLight.jpg',
  },
  {
    id: 11,
    category: 'Lamps',
    title: 'Light for All Times',
    price: 125,
    img: './furnitures/lamps_lightForAllTimes.jpg',
  },
  {
    id: 12,
    category: 'Sofas',
    title: 'Optimal Choice',
    price: 1400,
    img: './furnitures/sofa_optimalChoice.jpg',
  },
  {
    id: 13,
    category: 'Sofas',
    title: 'Lost World',
    price: 2500,
    img: './furnitures/sofa_lostWorld.jpg',
  },
  {
    id: 14,
    category: 'Sofas',
    title: 'Space Conqueror',
    price: 2500,
    img: './furnitures/sofa_spaceConqueror.jpg',
  },
  {
    id: 15,
    category: 'Sofas',
    title: 'Little Dream',
    price: 2500,
    img: './furnitures/sofa_littleDream.jpg',
  },
];
